### ISSUE TITLE
전체적인 코드 리팩토링

### ISSUE THREAD

**Issue by mingmingmon** [Mu-necting/Mu-necting_Server_V4#31]
## Describe
기획이 수정되면서 불필요한 코드가 많이 존재합니다. 이를 삭제하고자 합니다.
어노테이션사용과 명명규칙을 정립해 일관성 있는 코드를 작성하고자 합니다.

## Task
- [x] 불필요한 코드 삭제
- [x] 코드 컨벤션 정립 후 적용

## 코드 컨벤션
- [x] 1. 엔드포인트 확인
- 복수형 명명규칙
- 논리에 맞는 계층 구조
- 스웨거에 작업 담당자 이름 작성
- URL 경로가 없더라도 `@PostMapping("")` 같이 표현
- URL 경로 끝에 `/` 제거
- 상태코드 200과 201 구분 확인
- [x] 2. `Transaction` 확인
- [x] 3. `RequestDto` 어노테이션 확인
- `@Builder` 제거
- [x] 4. RequestDto 검증 어노테이션 추가
- [x] 5. requestDto를 `record` 자료형으로 수정, responseDto도 `record`로 수정하고 `@Builder`를 사용
- [x] 6. Entity에 `@Setter` 삭제
- [x] 7. dto를 생성하는 static 메소드의 경우는 `of`를 사용하고 `@Builder`로 처리
- [x] 8. dto의 필드는 모두 Wrapper 클래스로 사용
- [x] 9. class를 둘러싼 { } 안의 코드는 위쪽에는 개행을 추가하고 아래쪽은 개행 없이. 의존필드와 dto 필드는 사이에 개행이 없는 것이 기본이지만 어노테이션이 있는 경우 위아래로 개행 추가
- [x] 10. record의 { }안에 내용이 없는 경우 한줄로 중괄호 처리
- [x] 11. dto 패키지 안에 requestDto, responseDto 디렉토리 분리하기
- [x] 12. 응답 시 반복되는`Status.getCode(), Status.getMessage()` 함수화
